### PR TITLE
Merging all changes from the past sprints until now.

### PR DESCRIPTION
**Pull request by DSep**
See previous PRs for details.

- App is now functional according to standard requirements. 
- Deployed. 
- Newly updated README as well.

### CODE REVIEW

**Review by yqj2k — DISMISSED** [review]
I approve of these changes so long nothing is broken from master!!!!

**Review by baconandchips — DISMISSED** [review]
After getting in new changes from develop, I think this should be fine. LGTM

**Review by baconandchips — DISMISSED** [review]
LGTM, I'd suggest merging it in now once at least so that most of the commits are there, and we can merge again later when/if we have more stuff for Master. Best not to have all the work still on Develop branch when the presentation rolls around I think; we can also setup another merge-to-master PRs immediately afterwards so that we can be reminded of this push too. If it's deployed, I think our commit should be good right now

**Review by beetai — APPROVED** [review]
finally

**Review by yqj2k — APPROVED** [review]
no comments needed.

**Pull request merged**
