### PR TITLE
major refactor to our codebase for long term development

### PR DESCRIPTION
**Pull request by yqj2k**

### CODE REVIEW

**Review by DSep — COMMENTED** [review]
Looks good!
Just one thing: does it make sense to contain all the functionality like browse/searching and course viewing within a _profile_ directory? I feel like those two don't really fall into the category, but I do like the idea of separating. So maybe they can be in their own dirs?

**Comment by yqj2k** [comment]
Maybe I should rename the profile directory... I do like the idea of keeping them together; I feel like these two are workflows/actions that the user would do.

**Comment by beetai** [comment]
I don't see a problem and all looks good to me, though I agree that it's worth discussing whether course search should be within profile. I was thinking maybe you'd have the profile be one folder and course search be another? Once this is sorted out I'm ready to approve this to merge.

**Comment by DSep** [comment]
Yeah, I feel your (Sam) page (to be renamed Home) would make the most sense under "Profile" and Guanting and I's pages would be more logical under the main directory. But also remember that these are Pages, more general than the Components within them, and much fewer of them to try to group by function. Perhaps it makes sense to not really be generating too many subdirs for the Pages?

**Comment by yqj2k** [comment]
I agree with you that Browse/Search is too general to be in another profile subdirectory, but I think they are components within a user's actions. I don't think they would be pages because our page should only refresh the user's actions (browsing, or course searching) all the while a navbar and other things on the page will remain the same.

So, why don't we put Browse/Search within the component folder for now, and for future iterations, if they do become standalone general components, why don't we create folders for themselves?

**Comment by DSep** [comment]
LGTM. 
@baconandchips 's components to be moved to Components later.

**Review by DSep — APPROVED** [review]
LGTM
@baconandchips 's VisualizeCourse pieces will need to be moved to Components later.

And all of our pages will be need to be modularized as much as reasonably possible later.

**Comment by baconandchips** [comment]
Looks good with me as well! I agree on the component move; will be doing that when I get off work. I think having Profile might be a bit general for the components as of now; maybe we can start off with having page components in folders for their respective pages under "Components" folder, and as we develop commonly-used components we can perhaps move them to the main "Components" folder, or we develop them directly in the "Components" folder. We can definitely discuss more in the meeting to agree on a standard

**Pull request merged**
